// --- FILE: src/auth/RegistrationPage.js ---
import { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom'; // if used
import { Mail, Lock, User } from 'lucide-react'; // or your icon library
import AuthLayout from '../AuthLayout'; // update path if different
import { useTheme } from '../ThemeContext'; 


const RegistrationPage = () => {
    const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [error, setError] = useState(''); const [success, setSuccess] = useState('');
    const handleRegister = (e) => { e.preventDefault(); setError(''); setSuccess(''); if(password!==confirmPassword){setError('Passwords do not match.');return;} if(password.length<6){setError('Password must be at least 6 characters long.');return;} setSuccess('Registration successful! Please log in.'); setName(''); setEmail(''); setPassword(''); setConfirmPassword(''); };
    return ( <AuthLayout><div className="bg-white/80 dark:bg-gray-800/80 backdrop-blur-sm p-8 rounded-xl shadow-2xl"><h2 className="text-2xl font-bold text-center text-gray-800 dark:text-white mb-6">Create Your Account</h2>{error&&<p className="bg-red-500/20 text-red-500 p-3 rounded-lg mb-4">{error}</p>}{success&&<p className="bg-green-500/20 text-green-500 p-3 rounded-lg mb-4">{success}</p>}<form onSubmit={handleRegister} className="space-y-6"><div className="relative"><User className="absolute top-1/2 left-3 -translate-y-1/2 text-gray-400"/><input type="text" placeholder="Full Name" value={name} onChange={e=>setName(e.target.value)} required className="w-full pl-10 pr-4 py-3 bg-gray-100 dark:bg-gray-700 rounded-lg"/></div><div className="relative"><Mail className="absolute top-1/2 left-3 -translate-y-1/2 text-gray-400"/><input type="email" placeholder="Email Address" value={email} onChange={e=>setEmail(e.target.value)} required className="w-full pl-10 pr-4 py-3 bg-gray-100 dark:bg-gray-700 rounded-lg"/></div><div className="relative"><Lock className="absolute top-1/2 left-3 -translate-y-1/2 text-gray-400"/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required className="w-full pl-10 pr-4 py-3 bg-gray-100 dark:bg-gray-700 rounded-lg"/></div><div className="relative"><Lock className="absolute top-1/2 left-3 -translate-y-1/2 text-gray-400"/><input type="password" placeholder="Confirm Password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} required className="w-full pl-10 pr-4 py-3 bg-gray-100 dark:bg-gray-700 rounded-lg"/></div><button type="submit" className="w-full bg-gradient-to-r from-[#FF4E00] to-[#F4743B] text-white font-bold py-3 rounded-lg">Create Account</button></form><p className="text-center text-gray-600 dark:text-gray-400 mt-6">Already have an account? <Link to="/login" className="font-bold text-[#F4743B] hover:underline">Login here</Link></p></div></AuthLayout> );
};
export default RegistrationPage;